polls2/urls.py
from django.conf.urls import url

from views import index, add_task, task_list, del_task, edit_task

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add_task, name='add_task'),
    url(r'^tasks/$', task_list, name='tasks'),
    url(r'^delete/(?P<pk>[0-9]+)/$', del_task, name='delete'),
    url(r'^edit/(?P<pk>[0-9]+)/$', edit_task, name='edit_task'),
]

task/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'task.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^', include('polls2.urls', namespace="task_manager")),
    url(r'^admin/', include(admin.site.urls)),
)

polls2/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    pub_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField('due date')
    modification_date = models.DateField(auto_now=True)

    
    def __str__(self):
        return self.name

    def delete_task(self):
        return reverse('task_manager:delete', args=(self.pk,))

    @property
    def task_edit(self):
    	return reverse('task_manager:edit_task', args=(self.pk,))

polls2/forms.py
from django import forms
from .models import Task

class FormTaskAdd(forms.ModelForm):
    name = forms.CharField(max_length=40)
    description = forms.CharField(widget=forms.Textarea, max_length=200)
    due_date = forms.CharField(max_length=40)

    class Meta:
    	model = Task
    	fields = ('name', 'description', 'due_date')

polls2/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .models import Task
from .forms import FormTaskAdd

def index(request):
    return render(request, 'polls2/index.html')

def add_task(request):
    if request.method == 'POST':
        form = FormTaskAdd(request.POST)
        if form.is_valid():
            # task = form.save(commit=False)
            form.save()
            return render(request, 'polls2/task_list.html')
    else:        
        form = FormTaskAdd()
    return render(request, 'polls2/add_task.html', {'form':form})

def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'polls2/task_list.html', {'task_list':tasks})

def del_task(request, pk):
    tasks = get_object_or_404(Task, pk = pk)
    tasks.delete()
    return HttpResponseRedirect("/tasks/")

def edit_task(request, pk):
    task = Task.objects.get(pk=pk)
    if request.POST:
        form=FormTaskAdd(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return render(request, 'polls2/task_list.html')
    else:
        form=FormTaskAdd(instance=task)

    return render(request, 'polls2/task_edit.html', {'form':form, 'task': task}) 

polls2/templates/index.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-editable.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/table.css" rel="stylesheet">

  </head>

<body>

<nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'task_manager:tasks' %}">List of Tasks</a></li>
              <li><a href="{% url 'task_manager:add_task' %}">Add New Task</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-editable.js"></script>
    <script src="{{ STATIC_URL }}js/editable.js"></script>

  </body>
</html>

polls2/templates/polls2/add_task.html
{% include "index.html" %}

{% block content %}

<form action="{% url 'task_manager:add_task' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

{% endblock content%}

polls2/templates/polls2/index.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-editable.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/table.css" rel="stylesheet">

  </head>

<body>

<nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'task_manager:tasks' %}">List of Tasks</a></li>
              <li><a href="{% url 'task_manager:add_task' %}">Add New Task</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      {% block content %}
      {% endblock%}
      
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script> 
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap-editable.js"></script>
    <script src="{{ STATIC_URL }}js/editable.js"></script>

  </body>
</html>

polls2/templates/polls2/task_edit.html
<form action="{% url 'task_manager:edit_task' task.id %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

polls2/templates/polls2/task_list.html
{% include "index.html" %}


{% block content %}


<table border="5" style="width:70%">
<tr>
    <th>Name</th>
    <th>Description</th> 
    <th>Due date</th>

  </tr>
    {% for task in task_list %}
    {% csrf_token %} 
    <tr>
        <td>{{ task.name }} </td> 
        <td>{{ task.description }} </td>
        <td>{{ task.due_date }}</td>
        <td><a href="{{ task.delete_task }}">Delete</a></td>
        <td><a href="{{ task.task_edit }}">Update</a></td>
    </tr>

    {% endfor %}
</table>
{% endblock %}